CREATE OR REPLACE FUNCTION GENERAR_IMC(
    PESO DOUBLE PRECISION,
    ESTATURA DOUBLE PRECISION
)
RETURNS DOUBLE PRECISION
LANGUAGE SQL
AS $$
    SELECT PESO / POWER(ESTATURA, 2);
$$;

CREATE OR REPLACE FUNCTION GENERAR_EXPEDIENTE(
    TELEFONO VARCHAR(10)
)
RETURNS VARCHAR
LANGUAGE SQL
AS $$
    SELECT REGEXP_REPLACE(TELEFONO, '(.)', '\1X', 'g');
$$;

SELECT GENERAR_IMC(72.5, 1.65)

SELECT GENERAR_EXPEDIENTE('557727704')

COMMIT;